### PR TITLE
don't include "undefined" in img classes

### LINKED ISSUE #47: "undefined" included in classes if className not specified
It looks like [this fix](https://github.com/KyleAMathews/react-gravatar/commit/b4a0449fc40753cc4cbbac1c84b5088351bb1eee) for #36 had the side-effect that if you don't specify the `className` prop then the `img` ends up with the class `"react-gravatar undefined"` which seems undesirable.

### PR DESCRIPTION
**Pull request by dylanscott**
This fixes #47 and also cleans up the handling of the `className` prop which seemed a bit confused. In particular, in the case that `@prop.className` was specified, the first `className` is overwritten by the spread `...@props` (which is desirable since it lets you overwrite the default `react-gravatar` class completely), so the only case where the `"react-gravatar " + @props.className` code was in play was when `@props.className` was undefined.

With that in mind this PR changes the code not to pass `className` explicitly and just always picks up the version spread in from the props, and sets the default value for `className` to `react-gravatar`.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hi, definitely like PRs :-)

I agree having undefined isn't ideal. But I'd rather react-gravatar always show up... so how about you set the default className prop to `""`? Your change is a breaking change and not really necessary IMO. Thoughts?

**Comment by dylanscott** [comment]
Changing the default to `""` would revert b4a0449fc40753cc4cbbac1c84b5088351bb1eee, which fixed #36.

I'm not sure that this change is breaking (unless people are styling the `.undefined` class, which would be pretty weird). The current behavior if you specify the `className` prop is that it will overwrite the explicitly specified `"react-gravatar " + @prop.className` value. As [the documentation](https://facebook.github.io/react/docs/jsx-spread.html#spread-attributes) on jsx-spread mentions "The specification order is important. Later attributes override previous ones.", and the `{...@props}` is specified last. I've verified locally that specifying `className` overwrites the react-gravatar class.

That having been said, I'm happy to update the PR to always include the react-gravatar class. Just want to be clear that that is a change from the current behavior.

**Comment by KyleAMathews** [comment]
Haha so we go a full circle.

So yes, however this is done, react-gravatar should always show up as a class and not get overwritten.

**Comment by dylanscott** [comment]
Sounds good - I've updated the PR not to override the `react-gravatar` class, and also avoid including `"undefined"` in there. We specify `className` after the `{...@props}` spread to avoid being overwritten.

**Comment by KyleAMathews** [comment]
:+1:

**Comment by KyleAMathews** [comment]
Published 2.4.3 with your fix, thanks!

**Comment by dylanscott** [comment]
Awesome, thanks for the super quick turnaround! :)

**Comment by KyleAMathews** [comment]
Well it's either I do it now or do it in 1 month so I figured I'd just push it out real quick :-)

**Pull request merged**
