### PR TITLE
Added a `defaultComponent` prop that handles missing Gravatar images.

### PR DESCRIPTION
**Pull request by cjke**
This (intentionally) only works when the `default` is set to "404".

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hi, could you change the API to just be `<Gravatar email="blahblah@blah.com" default="404" defaultComponent={AppAvatar} />`? This way you wouldn't need to clone the component. Also this is the pattern I see other components using.

**Comment by cjke** [comment]
Hey. Totally cool with that, but can I flag the thinking - by passing in just AppAvatar you are actually limiting the functionality of the passed in component dramatically. For example, lets say I want to give it a class - 

`<Gravatar email="blahblah@blah.com" default="404" defaultComponent={<AppAvatar className="AppAvatar--blue" />} />`

~~Secondly, by passing in just `AppAvatar` you need to some funky case juggling.~~

*Edit* Actually ignore the second point. That's only relevant from a dynamic string lookup

Also cloneElement isn't super expensive, as per the comment (acemarke is https://github.com/markerikson)
https://www.reddit.com/r/reactjs/comments/53uk7v/cloning_elements_expensive/

Some libs do lean towards it: https://ant.design/components/card/ (see basic example "extra" prop)

I guess if it the suggest pattern `defaultComponent={AppAvatar}`, will need to look at it accepting a function callback as well, so you could do something like `defaultComponent={() => <AppAvatar className="blue" />}`

Your call at the end of the day!

**Comment by cjke** [comment]
I'm going to close this - I ended up pushing all the functionality to the backend to pre validate images before hitting the front

**Comment by IsenrichO** [comment]
@cjke @KyleAMathews Could we reopen this PR? This is the exact fallback functionality my team is looking for.

**Pull request closed without merging**
