### PR TITLE
ability to specify md5 manually

### PR DESCRIPTION
**Pull request by indeyets**
Sometimes, it is desirable not to expose emails to the code.
Solution is to be able to generate md5 on the server side and give it to component directly

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Totally! This would be a simple fix if you'd like to put together a PR.

**Comment by indeyets** [comment]
@KyleAMathews see commit above. the code is not checked. I rarely touch coffeescript and do not have tooling around, but should be mostly fine

**Comment by KyleAMathews** [comment]
Ooops! Haha, I was looking on my email and missed that this _was_ a PR :D

**Comment by indeyets** [comment]
initially it wasn't :) I converted it into one

**Comment by KyleAMathews** [comment]
Ahh! Sneaky :)

**Comment by KyleAMathews** [comment]
So looking at the PR, email is still required which it isn't correct any longer. Since email and the md5 hash are optional, perhaps add a check in the render function that either email or md5 is passed in and do a console.warn if they're both missing.

**Comment by indeyets** [comment]
like this?

**Comment by KyleAMathews** [comment]
How about you change the warning text from "Neither "email" or "md5" parameters are specified" to 'Either the "email" or "md5" prop must be specified.'

**Comment by indeyets** [comment]
done

**Comment by KyleAMathews** [comment]
One last fix needed. I'd not set a default value for the md5/email props as right now, even if neither props are passed into the component, the if check will still think they're set. Not setting a default prop will leave them as undefined.

**Comment by indeyets** [comment]
and… done

**Comment by KyleAMathews** [comment]
thanks!

**Comment by KyleAMathews** [comment]
Published 2.1.0

**Pull request merged**
