### PR TITLE
Sets email to Gravatar service recommended lowercase format.

### PR DESCRIPTION
**Pull request by AlexanderNull**
Issue 86

Follows recommended Gravatar steps for creating an md5 hash that matches their system hash:

> Trim leading and trailing whitespace from an email address
> Force all characters to lower-case
> md5 hash the final string

### CODE REVIEW

**Comment by satazor** [comment]
@KyleAMathews can you look review and merge? Please see: https://github.com/npms-io/npms-www/issues/107

**Comment by KyleAMathews** [comment]
@satazor thanks for the reminder! Though NPM isn't using react-gravatar.

**Comment by satazor** [comment]
Not npm, npms.io. I'm using your library in the npms.io website

**Comment by KyleAMathews** [comment]
@satazor ah nice!

**Pull request merged**
